from PIL import Image
import os
import sys
name = sys.argv[1]#"serpinski nGon6"
screensize = int(sys.argv[2])#8000
print("combining now...")
if (len(sys.argv) < 4 or sys.argv[3] == 2):
    img = Image.new("RGB",(screensize*2,screensize*2))
    imtr = Image.open(name+"Tl.jpg")
    img.paste(imtr,(0,0))
    imtr = Image.open(name+"Tr.jpg")
    img.paste(imtr,(screensize-1,0))
    imtr = Image.open(name+"Bl.jpg")
    img.paste(imtr,(0,screensize))
    imtr = Image.open(name+"Br.jpg")
    img.paste(imtr,(screensize-1,screensize))
    img.save(name+".jpg")
    print("finished combining, removing extra files")
    os.system("del \"" + name+"Tr.jpg" + "\"")
    os.system("del \"" + name+"Br.jpg" + "\"")
    os.system("del \"" + name+"Tl.jpg" + "\"")
    os.system("del \"" + name+"Bl.jpg" + "\"")
    print("all done!")
    os.system("\""+name+".jpg\"")
elif (sys.argv[3] == "3"):
    img = Image.new("RGB",(screensize*3,screensize*3))
    img2 = Image.open(name+"0.png")
    img.paste(img2,(0,0))
    img2 = Image.open(name+"1.png")
    img.paste(img2,(screensize,0))
    img2 = Image.open(name+"2.png")
    img.paste(img2,(screensize*2,0))
    img2 = Image.open(name+"3.png")
    img.paste(img2,(0,screensize))
    img2 = Image.open(name+"4.png")
    img.paste(img2,(screensize,screensize))
    img2 = Image.open(name+"5.png")
    img.paste(img2,(screensize*2,screensize))
    img2 = Image.open(name+"6.png")
    img.paste(img2,(0,screensize*2))
    img2 = Image.open(name+"7.png")
    img.paste(img2,(screensize,screensize*2))
    img2 = Image.open(name+"8.png")
    img.paste(img2,(screensize*2,screensize*2))
    img.save(name+".png")
    print("finished combining, removing extra files")
    os.system("del \"" + name+"0.png" + "\"")
    os.system("del \"" + name+"1.png" + "\"")
    os.system("del \"" + name+"2.png" + "\"")
    os.system("del \"" + name+"3.png" + "\"")
    os.system("del \"" + name+"4.png" + "\"")
    os.system("del \"" + name+"5.png" + "\"")
    os.system("del \"" + name+"6.png" + "\"")
    os.system("del \"" + name+"7.png" + "\"")
    os.system("del \"" + name+"8.png" + "\"")
    print("all done!")
    os.system("\""+name+".png\"")